### ISSUE TITLE
[BUG] undefined method `raw' for an instance of Rswag::Ui::Configuration

### ISSUE THREAD

**Issue by khataev** [rswag/rswag#808]
## Describe the bug
Error is thrown when trying to access `api-docs/index.html` endpoint

## Steps to Test or Reproduce
1. Write rswag specs
2. Generate swagger.json `using rswag:specs:swaggerize` rake task
3. Start rails server
4. Access localhost:3000/api-docs/index.html
5. Observe error 

## Expected behavior
Should see open api documentation

## Screenshots
<img width="790" alt="Screen Shot 2024-12-21 at 5 58 38 PM" src="https://github.com/user-attachments/assets/e9c6132c-1c39-4c48-96f1-fdd1b0990c46" />

## Additional context
gem "rswag-api"                                                                                                        
gem "rswag-ui"  
gem "rswag-specs" 

Everything worked on ruby 2.7.4 (I've just checked by checking out the old code) and most likely broke with upgrade to ruby 3.x. This documentation was not used for a while, this is why we haven't noticed it right away.

## Dependency versions
The version of are you using for:
* Rswag 2.16.0:
* RSpec 3.13.0:
* Rails 7.1.5.1:
* Ruby 3.3.5:

## Relates to which version of OAS (OpenAPI Specification)
- [ ] OAS2
- [ ] OAS3
- [ ] OAS3.1

**Comment by khataev** [comment]
Any updates here, is there a chance it will be fixed soon? @romanblanco
