### ISSUE TITLE
Tests failing since updating to 1.5

### ISSUE THREAD

**Issue by seriousbee** [rswag/rswag#95]
I recently wrote over 40 tests on 8 endpoints using RSwag 1.4. All of them were passing except for POST which used formData. I soon discovered that this is supported from version 1.5 which motivated me to update. However, ever since I updated, none of my tests pass, most exiting with code 
```
Failure/Error: assert_response_matches_metadata(metadata)
     NameError:
       undefined local variable or method `metadata' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1::Nested_2::Nested_1::Nested_2:0x0000000e667b38>
     # /var/lib/gems/2.1.0/gems/rspec-expectations-2.14.3/lib/rspec/matchers/method_missing.rb:9:in `method_missing'
     # /var/lib/gems/2.1.0/gems/actionpack-3.2.22.3/lib/action_dispatch/testing/assertions/routing.rb:176:in `method_missing'
     # /var/lib/gems/2.1.0/gems/actionpack-3.2.22.3/lib/action_dispatch/testing/integration.rb:386:in `method_missing'
     # /var/lib/gems/2.1.0/gems/rswag-specs-1.5.0/lib/rswag/specs/example_group_helpers.rb:80:in `block in run_test!'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:114:in `instance_eval'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:114:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:111:in `run'

```

_NOTE: I tried 1.5 version as well, but it fails in the same way._ 

Has the way of writing Specs changed from 1.4 to 1.5 in any way?  Or maybe the compatibility with RSpec 2.14 has been broken?

**Comment by domaindrivendev** [comment]
Can you provide the test code for an example that's failing?

**Comment by domaindrivendev** [comment]
Certainly looks like an rspec 2 compatibility issue. In rspec2, if you're using the rswag assert helpers, you need to call them as follows:

```ruby
before do |example|
  submit_request(example.metadata)
end

it 'does something' do |example|
  assert_response_matches_metadata(example.metadata)
end
```

Try this if you haven't already - although this should always have been necessary, even prior to rswag 1.5.0.

**Comment by seriousbee** [comment]
This is the code for my tests:

```
require 'swagger_helper'

describe 'Pets API', type: :request, swagger_doc: 'v1/swagger.json' do

  before do
    @user = create(:user, kind: :api)
    @auth_token = @user.get_key
  end

  path '/pets/{pet_id}/performances' do
    get 'Retrieves list of Pet\'s performances' do
      tags 'Performances'
      parameter name: 'pet_id', :in => :path, :type => :string
      parameter name: 'Authorization', :in => :header, :type => :string, :required => true
      parameter name: 'Accept', :in => :header, :type => :string, :description => 'Defining version of API to call', :required => true
      description 'List of performances the pet has given'

      response '200', 'OK' do
        schema type: :array, items: { '$ref' => '#/definitions/Performance'}
        let ('Authorization') {@auth_token}
        let ('Accept') {'application/pets.api.v1+json'}
        let ('pet_id') {'PET1'}
        before do
          FactoryGirl.create(:pet_with_performance, :id => 'PET1')
        end
        run_test!
      end

      response '404', 'performances not found' do
        schema '$ref' => '#/definitions/Error'
        let ('Authorization') {@auth_token}
        let ('Accept') {'application/pets.api.v1+json'}
        let ('pet_id') {'PET1'}
        run_test!
      end
    end
  end

  path '/pets/{pet_id}/performances/{id}' do
    get 'Details of a Pet\'s performance' do
      tags 'Performances'
      parameter name: 'pet_id', :in => :path, :type => :string
      parameter name: 'id', :in => :path, :type => :string
      parameter name: 'Authorization', :in => :header, :type => :string, :required => true
      parameter name: 'Accept', :in => :header, :type => :string, :description => 'Defining version of API to call', :required => true
      description 'Details of a single performance'

      response '200', 'OK' do
        schema type: :array, items: { '$ref' => '#/definitions/Performance'}
        let ('Authorization') {@auth_token}
        let ('Accept') {'application/pets.api.v1+json'}
        let ('pet_id') {'PET1'}
	let ('id') {Performance.all[0].id}
        before do
          FactoryGirl.create(:pet_with_performance, :id => 'PET1')
        end
        run_test!
      end


      response '404', 'performances not found' do
        schema '$ref' => '#/definitions/Error'
        let ('Authorization') {@auth_token}
        let ('Accept') {'application/pets.api.v1+json'}
        let ('pet_id') {'PET1'}
        let('id') {'2'}
        run_test!
      end
    end
  end
end

```


Every single test case fails with the same error:
```
NameError:
       undefined local variable or method `metadata' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1::Nested_1::Nested_2:0x0000000f1ca728>
     # /var/lib/gems/2.1.0/gems/rspec-expectations-2.14.3/lib/rspec/matchers/method_missing.rb:9:in `method_missing'
     # /var/lib/gems/2.1.0/gems/actionpack-3.2.22.3/lib/action_dispatch/testing/assertions/routing.rb:176:in `method_missing'
     # /var/lib/gems/2.1.0/gems/actionpack-3.2.22.3/lib/action_dispatch/testing/integration.rb:386:in `method_missing'
     # /var/lib/gems/2.1.0/gems/rswag-specs-1.5.1/lib/rswag/specs/example_group_helpers.rb:82:in `block in run_test!'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:114:in `instance_eval'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:114:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example.rb:111:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:386:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:371:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/example_group.rb:372:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:28:in `map'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:28:in `block in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/reporter.rb:58:in `report'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:25:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:77:in `rescue in run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:73:in `run'
     # /var/lib/gems/2.1.0/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by seriousbee** [comment]
Hi @domaindrivendev, I applied your suggestion and my code looks now the following way:

```require 'swagger_helper'
describe 'Pets API', type: :request, swagger_doc: 'v1/swagger.json' do

  before do
    @user = create(:user, kind: :api)
    @auth_token = @user.get_key
  end

  path '/pets/{pet_id}/performances' do
    get 'Retrieves list of Pet\'s performances' do
      tags 'Performances'
      parameter name: 'pet_id', :in => :path, :type => :string
      parameter name: 'Authorization', :in => :header, :type => :string, :required => true
      parameter name: 'Accept', :in => :header, :type => :string, :description => 'Defining version of API to call', :required => true
      description 'List of performances the pet has given'

      response '200', 'OK' do
        schema type: :array, items: { '$ref' => '#/definitions/Performance'}
        let ('Authorization') {@auth_token}
        let ('Accept') {'application/pets.api.v1+json'}
        let ('pet_id') {'PET1'}

	before do |example|
          FactoryGirl.create(:pet_with_performance, :id => 'PET1')
          submit_request(example.metadata)
        end

	it 'returns a valid 200 response' do |example|
          assert_response_matches_metadata(example.metadata)
        end
      end
    end
  end
end
```

Sadly the only thing this changes is shortening the error message to:

```
Failure/Error: submit_request(example.metadata)
NoMethodError:
undefined method 'metadata' for #<RSpec::Core::ExampleGroup::Nested_1::Nested_1::Nested_1::Nested_1:0x0000000a04aa10>
```

This error comes up regardless if run using RSwag 1.4 or 1.5. If I use run_test! instead, as I showed in the previous post, the tests pass in 1.4.

**Comment by BookOfGreg** [comment]
I'm going to close this as it's stale and there's been a major version since here.
Willing to re-open the discussion and see what we can do to fix if there's still demand for it.
