### ISSUE TITLE
Can't use "operation_description"

### ISSUE THREAD

**Issue by benoittgt** [rswag/rswag#25]
Hello

Thanks a lot for `swagger_rails`. It's very great to use.

I have an issue when trying to use `operation_description` :

``` ruby
get 'user stores' do
      operation_description 'Detailed implementation notes for the create a new blog API endpoint'
      consumes 'application/json'
```

```
/Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:656:in `method_missing': undefined method `operation_description' for #<Class:0x007fdf446a29f0> (NoMethodError)
    from /Users/bti/code/appaloosa/spec/requests/mobile/stores_controller_spec.rb:21:in `block (3 levels) in <top (required)>'
    from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `module_exec'
    from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:363:in `subclass'
    from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/rspec-core-3.3.2/lib/rspec/core/example_group.rb:254:in `block in define_example_group_method'
    from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/rspec/dsl.rb:20:in `operation'
    from /Users/bti/.rvm/gems/ruby-2.3.0@appaloosa/gems/swagger_rails-1.0.0.pre.beta2/lib/swagger_rails/rspec/dsl.rb:25:in `block (2 levels) in <module:DSL>'
```

Any idea?

**Comment by benoittgt** [comment]
Work perfectly with `swagger_rails (1.0.1.pre.beta3)`
